CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_USBD_LOG_LEVEL_WRN=y
CONFIG_USBD_THREAD_STACK_SIZE=4096
CONFIG_USBD_CDC_ACM_CLASS=y
CONFIG_USBD_CDC_ACM_LOG_LEVEL_OFF=y

CONFIG_SERIAL=y
CONFIG_UART_LINE_CTRL=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_UART_USE_RUNTIME_CONFIGURE=y

CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3


# enable CB_ZEPHYR_MODULE
CONFIG_CB_ZEPHYR_MODULE=y

# enable CB_ERROR module to get error handling and reporting features
CONFIG_CB_ERROR=y

# enable CB_SYS module to get system check functions and LED control features
CONFIG_CB_SYS=y
# CONFIG_CB_SYS_LED_BLINK=y
CONFIG_CB_SYS_LED_HEARTBEAT=y
CONFIG_CB_SYS_LED_BPM=40

# enable CB_INFO module to get build and system information features
CONFIG_CB_INFO=y